############################################################################
# examples/stepperd/Makefile
############################################################################

include $(APPDIR)/Make.defs
include $(SDKDIR)/Make.defs

PROGNAME = $(CONFIG_EXAMPLES_STEPPERD_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_STEPPERD_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_STEPPERD_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_STEPPERD)

ASRCS =
CSRCS =
MAINSRC = stepperd_main.c

include $(APPDIR)/Application.mk
