############################################################################
# examples/stepping_motor/Makefile
############################################################################

include $(APPDIR)/Make.defs
include $(SDKDIR)/Make.defs

PROGNAME = $(CONFIG_EXAMPLES_STEPPING_MOTOR_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_STEPPING_MOTOR_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_STEPPING_MOTOR_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_STEPPING_MOTOR)

ASRCS =
CSRCS =
MAINSRC = stepping_motor_main.c

include $(APPDIR)/Application.mk
